---
- name: Configurar servidor web
  hosts: all
  become: true
  tasks:
    - name: Instalar paquetes del sistema
      shell: apt update && apt install -y nginx curl htop

    - name: Asegurar que nginx este corriendo
      service:
        name: nginx
        state: started