---
- name: Configurar servidor web
  hosts: all
  become: true
  tasks:
    - name: Instalar paquetes del sistema de forma idempotente
      ansible.builtin.apt:
        name:
          - nginx
          - curl
          - htop
        state: present
        update_cache: true

    - name: Asegurar que nginx este corriendo
      ansible.builtin.service:
        name: nginx
        state: started